INSERT INTO MEMBER (ID, NICKNAME, PASSWORD, EMAIL, CREATED_DATE, UPDATED_DATE) VALUES (default, 'user1', '$2a$10$RipmJ2.1x5wRiO5Dx4a2SeAZRfWDiKCQEezI9TzAiP5yAfiH5jIhK', 'nana@naver.com', NOW(), NOW());
INSERT INTO MEMBER (ID, NICKNAME, PASSWORD, EMAIL, CREATED_DATE, UPDATED_DATE) VALUES (default, 'user2', '$2a$10$9bixt37laSFs1yvC6F/b9u4WUNqaJVRcxLPdjJU2vAZBDnxgmzmxq', 'nana2@naver.com', NOW(), NOW());

INSERT INTO RECIPE (ID, TITLE, CONTENT, MEMBER_ID,CREATED_DATE, UPDATED_DATE) VALUES (default,'TITLE1', 'CONTENT1', 1 ,NOW(), NOW());
INSERT INTO RECIPE (ID, TITLE, CONTENT, MEMBER_ID,CREATED_DATE, UPDATED_DATE) VALUES (default,'TITLE2', 'CONTENT2', 1 ,NOW(), NOW());
INSERT INTO RECIPE (ID, TITLE, CONTENT, MEMBER_ID,CREATED_DATE, UPDATED_DATE) VALUES (default,'TITLE3', 'CONTENT3', 1 ,NOW(), NOW());
INSERT INTO RECIPE (ID, TITLE, CONTENT, MEMBER_ID,CREATED_DATE, UPDATED_DATE) VALUES (default,'TITLE4', 'CONTENT4', 2 ,NOW(), NOW());
INSERT INTO RECIPE (ID, TITLE, CONTENT, MEMBER_ID,CREATED_DATE, UPDATED_DATE) VALUES (default,'TITLE5', 'CONTENT5', 2 ,NOW(), NOW());
INSERT INTO RECIPE (ID, TITLE, CONTENT, MEMBER_ID,CREATED_DATE, UPDATED_DATE) VALUES (default,'TITLE6', 'CONTENT6', 2 ,NOW(), NOW());

INSERT INTO INGREDIENT (id, name) VALUES (default, '양파');
INSERT INTO INGREDIENT (id, name) VALUES (default, '마늘');
INSERT INTO INGREDIENT (id, name) VALUES (default, '당근');
INSERT INTO INGREDIENT (id, name) VALUES (default, '파');
INSERT INTO INGREDIENT (id, name) VALUES (default, '고추');
INSERT INTO INGREDIENT (id, name) VALUES (default, '감자');
INSERT INTO INGREDIENT (id, name) VALUES (default, '토마토');
INSERT INTO INGREDIENT (id, name) VALUES (default, '오이');
INSERT INTO INGREDIENT (id, name) VALUES (default, '양배추');
INSERT INTO INGREDIENT (id, name) VALUES (default, '시금치');
